import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MoviesService {

  constructor() { }

  private movies = [
    {id: 2, "title":"Godzilla Minus One","year":"2023","rated":"PG-13","released":"01 Dec 2023","runtime":"124 min","genre":"Action, Adventure, Drama","director":"Takashi Yamazaki","writer":"Ishirô Honda, Takeo Murata, Takashi Yamazaki","actors":"Sakura Andô, Minami Hamabe, Ryunosuke Kamiki","plot":"Post war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.","language":"Japanese","country":"Japan","awards":"Nominated for 1 Oscar. 24 wins & 58 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BOTI5MjNjMTMtN2NiNC00YjBlLTgzMWQtMGRhZDZkYmY1NGU2XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg"}
  ,
  {id: 5,"title":"The Boy and the Heron","year":"2023","rated":"PG-13","released":"08 Dec 2023","runtime":"124 min","genre":"Animation, Adventure, Drama","director":"Hayao Miyazaki","writer":"Hayao Miyazaki","actors":"Soma Santoki, Masaki Suda, Kô Shibasaki","plot":"In the wake of his mother's death and his father's remarriage, a headstrong boy named Mahito ventures into a dreamlike world shared by both the living and the dead.","language":"Japanese, English","country":"Japan","awards":"Won 1 Oscar. 31 wins & 84 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BZjZkNThjNTMtOGU0Ni00ZDliLThmNGUtZmMxNWQ3YzAxZTQ1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg"}
  ,
  {id: 1,"title":"Dune: Part Two","year":"2024","rated":"PG-13","released":"01 Mar 2024","runtime":"166 min","genre":"Action, Adventure, Drama","director":"Denis Villeneuve","writer":"Denis Villeneuve, Jon Spaihts, Frank Herbert","actors":"Timothée Chalamet, Zendaya, Rebecca Ferguson","plot":"Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.","language":"English","country":"United States, Canada","awards":"2 nominations","poster":"https://m.media-amazon.com/images/M/MV5BODdjMjM3NGQtZDA5OC00NGE4LWIyZDQtZjYwOGZlMTM5ZTQ1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"}
  ,
  {id: 6,"title":"Anyone But You","year":"2023","rated":"R","released":"22 Dec 2023","runtime":"103 min","genre":"Comedy, Romance","director":"Will Gluck","writer":"Ilana Wolpert, Will Gluck","actors":"Sydney Sweeney, Glen Powell, Alexandra Shipp","plot":"After an amazing first date, Bea and Ben's fiery attraction turns ice-cold--until they find themselves unexpectedly reunited at a wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.","language":"English","country":"United States, Australia","awards":"1 win & 4 nominations","poster":"https://m.media-amazon.com/images/M/MV5BOTVhZGU2OWQtNDM1Ni00MzM3LTgzYjgtOTEwYzQzOWZjNTIyXkEyXkFqcGdeQXVyMTcwOTQzOTYy._V1_SX300.jpg"}
  ,
  {id: 7,"title":"All of Us Strangers","year":"2023","rated":"R","released":"22 Dec 2023","runtime":"105 min","genre":"Drama, Fantasy, Romance","director":"Andrew Haigh","writer":"Andrew Haigh, Taichi Yamada","actors":"Andrew Scott, Paul Mescal, Carter John Grout","plot":"A screenwriter drawn back to his childhood home enters into a fledgling relationship with his downstairs neighbor while discovering a mysterious new way to heal from losing his parents 30 years ago.","language":"English","country":"United Kingdom, United States","awards":"Nominated for 6 BAFTA 25 wins & 104 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BZmYzMjMzN2EtMGYwNi00ODc3LWI3YTctMjA5YjI1MGFkYTlhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg"}
  ,
  {id: 8,"title":"Poor Things","year":"2023","rated":"R","released":"27 Feb 2024","runtime":"141 min","genre":"Comedy, Drama, Romance","director":"Yorgos Lanthimos","writer":"Tony McNamara, Alasdair Gray","actors":"Emma Stone, Mark Ruffalo, Willem Dafoe","plot":"The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.","language":"English, French, Portuguese","country":"Ireland, United Kingdom, United States, Hungary","awards":"Nominated for 11 Oscars. 93 wins & 408 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BNGIyYWMzNjktNDE3MC00YWQyLWEyMmEtN2ZmNzZhZDk3NGJlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg"}
  ,
  {id: 9,"title":"Kung Fu Panda 4","year":"2024","rated":"PG","released":"08 Mar 2024","runtime":"94 min","genre":"Animation, Action, Adventure","director":"Mike Mitchell, Stephanie Stine","writer":"Jonathan Aibel, Glenn Berger, Darren Lemke","actors":"Jack Black, Awkwafina, Viola Davis","plot":"After Po is tapped to become the Spiritual Leader of the Valley of Peace, he needs to find and train a new Dragon Warrior, while a wicked sorceress plans to re-summon all the master villains whom Po has vanquished to the spirit re...","language":"Mandarin, Chinese, English","country":"United States, China","awards":"N/A","poster":"https://m.media-amazon.com/images/M/MV5BZDY0YzI0OTctYjVhYy00MTVhLWE0NTgtYTRmYTBmOTE3YTViXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg"}
  ,
  {id: 10,"title":"Mean Girls","year":"2024","rated":"PG-13","released":"12 Jan 2024","runtime":"112 min","genre":"Comedy, Musical","director":"Samantha Jayne, Arturo Perez Jr.","writer":"Tina Fey, Rosalind Wiseman","actors":"Angourie Rice, Reneé Rapp, Auli'i Cravalho","plot":"Cady Heron is a hit with the Plastics, an A-list girl clique at her new school. But everything changes when she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.","language":"English","country":"United States","awards":"2 nominations","poster":"https://m.media-amazon.com/images/M/MV5BNDExMGMyN2QtYjRkZC00Yzk1LTkzMDktMTliZTI5NjQ0NTNkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg"}
  ,
  {id: 11,"title":"Demon Slayer: Kimetsu No Yaiba - To the Swordsmith Village","year":"2023","rated":"R","released":"03 Mar 2023","runtime":"110 min","genre":"Animation, Action, Adventure","director":"Haruo Sotozaki","writer":"Koyoharu Gotouge","actors":"Zach Aguilar, Laila Berzins, Kira Buckland","plot":"Tanjiro needs to bring a definitive end to Upper Rank Six. After the dust settles, he goes with his sister Nezuko to the Swordsmith Village in search of a new sword.","language":"Japanese","country":"Japan","awards":"1 nomination","poster":"https://m.media-amazon.com/images/M/MV5BZDZiZTZhMzgtYTY0ZC00OGUyLWE2NzgtMmM4MjA1YjUxN2YyXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_SX300.jpg"}
  ,
  {id: 3,"title":"Past Lives","year":"2023","rated":"PG-13","released":"23 Jun 2023","runtime":"105 min","genre":"Drama, Romance","director":"Celine Song","writer":"Celine Song","actors":"Greta Lee, Teo Yoo, John Magaro","plot":"Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates from South Korea. Twenty years later, they are reunited for one fateful week as they confront notions of love and destiny.","language":"Korean, English, Mandarin, French","country":"United States, South Korea","awards":"Nominated for 2 Oscars. 77 wins & 219 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BOTkzYmMxNTItZDAxNC00NGM0LWIyODMtMWYzMzRkMjIyMTE1XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg"}
  ,
  {id: 12,"title":"The Zone of Interest","year":"2023","rated":"PG-13","released":"20 Feb 2024","runtime":"105 min","genre":"Drama, History, War","director":"Jonathan Glazer","writer":"Jonathan Glazer, Martin Amis","actors":"Christian Friedel, Sandra Hüller, Johann Karthaus","plot":"Auschwitz commandant Rudolf Höss and his wife Hedwig strive to build a dream life for their family in a house and garden beside the camp.","language":"German, Polish, Yiddish","country":"United States, United Kingdom, Poland","awards":"Won 2 Oscars. 55 wins & 155 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BYzRmOGQwZjktYjM2Ni00M2NmLWFlZDYtZGFhM2RkM2VhZDI1XkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_SX300.jpg"}
  ,
  {id: 13,"title":"Turning Red","year":"2022","rated":"PG","released":"11 Mar 2022","runtime":"100 min","genre":"Animation, Adventure, Comedy","director":"Domee Shi","writer":"Domee Shi, Julia Cho, Sarah Streicher","actors":"Rosalie Chiang, Sandra Oh, Ava Morse","plot":"A thirteen-year-old girl named Mei Lee is torn between staying her mother's dutiful daughter and the changes of adolescence. And as if the challenges were not enough, whenever she gets overly excited she transforms into a giant re...","language":"English, Cantonese, Korean","country":"United States, Canada","awards":"Nominated for 1 Oscar. 10 wins & 91 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BOWYxZDMxYWUtNjNiZC00MDE1LWI2Y2QtNWZhNDAyMGY5ZjVhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"}
  ,
  {id: 14,"title":"Anatomy of a Fall","year":"2023","rated":"R","released":"22 Mar 2024","runtime":"151 min","genre":"Crime, Drama, Thriller","director":"Justine Triet","writer":"Justine Triet, Arthur Harari","actors":"Sandra Hüller, Swann Arlaud, Milo Machado-Graner","plot":"A woman is suspected of murder after her husband's death; their half-blind son faces a moral dilemma as the main witness.","language":"French, English, German","country":"France","awards":"Nominated for 5 Oscars. 90 wins & 189 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BMDBiYmRkNjUtYzc4My00NGFiLWE2NWUtMGU1ZDA1NTQ3ZjQwXkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_SX300.jpg"}
  ,
  {id: 15,"title":"Everything Everywhere All at Once","year":"2022","rated":"R","released":"08 Apr 2022","runtime":"139 min","genre":"Action, Adventure, Comedy","director":"Daniel Kwan, Daniel Scheinert","writer":"Daniel Kwan, Daniel Scheinert","actors":"Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis","plot":"A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.","language":"English, Mandarin, Cantonese","country":"United States","awards":"Won 7 Oscars. 402 wins & 373 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg"}
  ,
  {id: 1,"title":"Barbie","year":"2023","rated":"PG-13","released":"21 Jul 2023","runtime":"114 min","genre":"Adventure, Comedy, Fantasy","director":"Greta Gerwig","writer":"Greta Gerwig, Noah Baumbach","actors":"Margot Robbie, Ryan Gosling, Issa Rae","plot":"Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.","language":"English, Spanish","country":"United States, United Kingdom","awards":"Won 1 Oscar. 188 wins & 423 nominations total","poster":"https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"}
    ]

  getMovies(): typeof this.movies {
    return this.movies
  }

  getMovie(index: number): (typeof this.movies)[number] {
    const idx = 0;
    if (index > this.movies.length - 1 || index < 0) {
      return this.movies[idx];
    }
    return this.movies[index];
  }
}
